[workspace]

members = [
    "agent"

, "client", "common", "server"]

resolver = "2"


[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.release.package.agent]
opt-level = "s"
strip = true
codegen-units = 1

